import './globals.scss';

import type { Metadata } from 'next';
import React from 'react';

type LayoutProps = {
  children: React.ReactNode;
};

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en" style={{ height: '100%', overflow: 'hidden' }}>
      <body
        style={{
          height: '100vh',
          width: '100vw',
          background: '#101010',
          color: '#FFF',
          overflow: 'hidden',
          position: 'relative',
          fontFamily:
            '"SF Pro Display", -apple-system, blinkmacsystemfont, "Segoe UI", roboto, sans-serif',
          margin: 0,
          padding: 0,
        }}
      >
        {children}
      </body>
    </html>
  );
}
